import yfinance as yf
import pandas as pd
import pandas_ta as ta
import urllib.request
import json

def get_nifty500_tickers():
    """Fetches the Nifty 500 tickers from NSE or falls back to a large hardcoded list."""
    try:
        url = "https://archives.nseindia.com/content/indices/ind_nifty500list.csv"
        req = urllib.request.Request(url, headers={'User-Agent': 'Mozilla/5.0'})
        with urllib.request.urlopen(req) as response:
            df = pd.read_csv(response)
            tickers = [str(sym) + ".NS" for sym in df['Symbol'].tolist()]
            if tickers:
                return tickers
    except Exception as e:
        print(f"Error fetching Nifty 500: {e}. Falling back to top 50.")
        pass
        
    # Fallback Top 50
    return [
        "RELIANCE.NS", "TCS.NS", "HDFCBANK.NS", "ICICIBANK.NS", "INFY.NS",
        "SBIN.NS", "BHARTIARTL.NS", "ITC.NS", "LT.NS", "BAJFINANCE.NS",
        "HINDUNILVR.NS", "KOTAKBANK.NS", "AXISBANK.NS", "ASIANPAINT.NS", "MARUTI.NS",
        "TITAN.NS", "SUNPHARMA.NS", "BAJAJFINSV.NS", "ULTRACEMCO.NS", "TATASTEEL.NS",
        "NTPC.NS", "POWERGRID.NS", "TATAMOTORS.NS", "M&M.NS", "NESTLEIND.NS",
        "WIPRO.NS", "TECHM.NS", "HCLTECH.NS", "ONGC.NS", "ADANIENT.NS",
        "GRASIM.NS", "HINDALCO.NS", "JSWSTEEL.NS", "COALINDIA.NS", "TATASTLLP.NS",
        "INDUSINDBK.NS", "CIPLA.NS", "BRITANNIA.NS", "APOLLOHOSP.NS", "EICHERMOT.NS",
        "DIVISLAB.NS", "TATACONSUM.NS", "BAJAJ-AUTO.NS", "HEROMOTOCO.NS", "DRREDDY.NS",
        "SHREECEM.NS", "BPCL.NS", "UPL.NS", "HDFCLIFE.NS", "SBILIFE.NS"
    ]

def fetch_stock_data(ticker_symbol, period="6mo", interval="1d"):
    """Fetches historical data and calculates technical indicators."""
    print(f"Fetching {period} {interval} data for {ticker_symbol}...")
    try:
        ticker = yf.Ticker(ticker_symbol)
        df = ticker.history(period=period, interval=interval)
        
        if df.empty:
            return None
            
        # Calculate Technical Indicators using pandas_ta
        df.ta.rsi(length=14, append=True)
        df.ta.macd(fast=12, slow=26, signal=9, append=True)
        df.ta.sma(length=20, append=True)
        df.ta.sma(length=50, append=True)
        df.ta.sma(length=200, append=True)
        df.ta.bbands(length=20, std=2, append=True)
        df.ta.atr(length=14, append=True)
        
        # Drop NaN values generated by moving averages
        df = df.dropna()
        
        # Fundamental Data (Only makes sense to pull for daily/long term context)
        fund = {}
        if interval == "1d":
            info = ticker.info
            fund = {
                "trailingPE": info.get("trailingPE", "N/A"),
                "forwardPE": info.get("forwardPE", "N/A"),
                "priceToBook": info.get("priceToBook", "N/A"),
                "debtToEquity": info.get("debtToEquity", "N/A"),
                "trailingEps": info.get("trailingEps", "N/A")
            }
        
        return {
            "symbol": ticker_symbol,
            "df": df,
            "info": fund,
            "interval": interval
        }
    except Exception as e:
        print(f"Error fetching data for {ticker_symbol}: {e}")
        return None

def screen_stocks(tickers):
    """
    Runs a fast pre-screening on all tickers using basic technical analysis.
    Returns a list of high-probability tickers for the AI to analyze deeply.
    """
    print(f"Pre-screening {len(tickers)} stocks...")
    high_prob_tickers = []
    
    # Process in batches to avoid overwhelming the system
    for i, ticker in enumerate(tickers):
        if i > 0 and i % 50 == 0:
            print(f"Screened {i}/{len(tickers)} stocks...")
            
        try:
            # Fetch minimal data for fast screening
            t = yf.Ticker(ticker)
            df = t.history(period="1mo", interval="1d")
            
            if df.empty or len(df) < 20:
                continue
                
            # Basic Indicators
            df.ta.rsi(length=14, append=True)
            df.ta.macd(fast=12, slow=26, signal=9, append=True)
            
            latest = df.iloc[-1]
            prev = df.iloc[-2]
            
            rsi = latest.get('RSI_14', 50)
            macd = latest.get('MACD_12_26_9', 0)
            macd_signal = latest.get('MACDs_12_26_9', 0)
            prev_macd = prev.get('MACD_12_26_9', 0)
            prev_signal = prev.get('MACDs_12_26_9', 0)
            
            # Condition 1: Oversold (RSI < 35) or Overbought (RSI > 65)
            rsi_interesting = rsi < 35 or rsi > 65
            
            # Condition 2: MACD Crossover (Bullish or Bearish)
            macd_bullish_cross = prev_macd <= prev_signal and macd > macd_signal
            macd_bearish_cross = prev_macd >= prev_signal and macd < macd_signal
            
            if rsi_interesting or macd_bullish_cross or macd_bearish_cross:
                high_prob_tickers.append(ticker)
                
        except Exception as e:
            continue
            
    print(f"Screening complete. Found {len(high_prob_tickers)} high-probability stocks.")
    return high_prob_tickers

def get_latest_news(ticker_symbol):
    """Fetches recent news titles for the stock using yfinance."""
    try:
        ticker = yf.Ticker(ticker_symbol)
        news = ticker.news
        headlines = [item['title'] for item in news[:5]]
        return headlines
    except:
        return []

def format_data_for_ai(stock_data, headlines):
    """Formats the latest stock data into a concise text block for the AI."""
    df = stock_data['df']
    latest = df.iloc[-1]
    prev = df.iloc[-2]
    
    # Extract latest indicator values
    rsi = round(latest.get('RSI_14', 0), 2)
    macd = round(latest.get('MACD_12_26_9', 0), 2)
    macd_signal = round(latest.get('MACDs_12_26_9', 0), 2)
    sma_20 = round(latest.get('SMA_20', 0), 2)
    sma_50 = round(latest.get('SMA_50', 0), 2)
    sma_200 = round(latest.get('SMA_200', 0), 2)
    atr = round(latest.get('ATRr_14', 0), 2)
    bb_lower = round(latest.get('BBL_20_2.0', 0), 2)
    bb_upper = round(latest.get('BBU_20_2.0', 0), 2)
    
    close_price = round(latest['Close'], 2)
    open_price = round(latest['Open'], 2)
    volume = latest['Volume']
    
    summary = f"""
Stock: {stock_data['symbol']}
Timeframe: {stock_data.get('interval', '1d')}
Day Open Price: {open_price}
Current Price: {close_price}
Previous Price: {round(prev['Close'], 2)}
Volume: {volume}

Technical Indicators:
- Volatility (ATR 14): {atr}
- RSI (14): {rsi}
- MACD (12, 26): {macd} (Signal: {macd_signal})
- Bollinger Bands (20): Lower {bb_lower}, Upper {bb_upper}
- SMA 20: {sma_20}
- SMA 50: {sma_50}
- SMA 200: {sma_200}
"""
    if stock_data.get('info'):
        info = stock_data['info']
        summary += f"""
Fundamental Data:
- Trailing P/E: {info.get('trailingPE')}
- Forward P/E: {info.get('forwardPE')}
- Price to Book: {info.get('priceToBook')}
- Debt to Equity: {info.get('debtToEquity')}
- Trailing EPS: {info.get('trailingEps')}
"""
    
    summary += "\nRecent News Headlines:\n"
    for h in headlines:
        summary += f"- {h}\n"
        
    return summary

if __name__ == "__main__":
    # Test the engine
    data = fetch_stock_data("RELIANCE.NS")
    if data:
        news = get_latest_news("RELIANCE.NS")
        text = format_data_for_ai(data, news)
        print(text)
