import yfinance as yf
import pandas as pd
import pandas_ta as ta
import urllib.request
import json

def get_nifty50_tickers():
    """Returns a sample list of top NSE tickers for analysis."""
    # NIFTY 50 Sample
    tickers = [
        "RELIANCE.NS", "TCS.NS", "HDFCBANK.NS", "ICICIBANK.NS", "INFY.NS",
        "SBIN.NS", "BHARTIARTL.NS", "ITC.NS", "LT.NS", "BAJFINANCE.NS"
    ]
    return tickers

def fetch_stock_data(ticker_symbol):
    """Fetches 6 months of historical daily data and calculates technical indicators."""
    print(f"Fetching data for {ticker_symbol}...")
    try:
        ticker = yf.Ticker(ticker_symbol)
        df = ticker.history(period="6mo")
        
        if df.empty:
            return None
            
        # Calculate Technical Indicators using pandas_ta
        df.ta.rsi(length=14, append=True)
        df.ta.macd(fast=12, slow=26, signal=9, append=True)
        df.ta.sma(length=20, append=True)
        df.ta.sma(length=50, append=True)
        df.ta.sma(length=200, append=True)
        
        # Drop NaN values generated by SMA 200
        df = df.dropna()
        
        return {
            "symbol": ticker_symbol,
            "df": df,
            "info": ticker.info
        }
    except Exception as e:
        print(f"Error fetching data for {ticker_symbol}: {e}")
        return None

def get_latest_news(ticker_symbol):
    """Fetches recent news titles for the stock using yfinance."""
    try:
        ticker = yf.Ticker(ticker_symbol)
        news = ticker.news
        headlines = [item['title'] for item in news[:5]]
        return headlines
    except:
        return []

def format_data_for_ai(stock_data, headlines):
    """Formats the latest stock data into a concise text block for the AI."""
    df = stock_data['df']
    latest = df.iloc[-1]
    prev = df.iloc[-2]
    
    # Extract latest indicator values
    rsi = round(latest.get('RSI_14', 0), 2)
    macd = round(latest.get('MACD_12_26_9', 0), 2)
    macd_signal = round(latest.get('MACDs_12_26_9', 0), 2)
    sma_20 = round(latest.get('SMA_20', 0), 2)
    sma_50 = round(latest.get('SMA_50', 0), 2)
    sma_200 = round(latest.get('SMA_200', 0), 2)
    
    close_price = round(latest['Close'], 2)
    open_price = round(latest['Open'], 2)
    volume = latest['Volume']
    
    summary = f"""
Stock: {stock_data['symbol']}
Day Open Price: {open_price}
Current Price: {close_price}
Previous Price: {round(prev['Close'], 2)}
Volume: {volume}

Technical Indicators:
- RSI (14): {rsi}
- MACD (12, 26): {macd} (Signal: {macd_signal})
- SMA 20: {sma_20}
- SMA 50: {sma_50}
- SMA 200: {sma_200}

Recent News Headlines:
"""
    for h in headlines:
        summary += f"- {h}\n"
        
    return summary

if __name__ == "__main__":
    # Test the engine
    data = fetch_stock_data("RELIANCE.NS")
    if data:
        news = get_latest_news("RELIANCE.NS")
        text = format_data_for_ai(data, news)
        print(text)
